### ISSUE TITLE
Accessibility issue/question

### ISSUE THREAD

**Issue by adi-b** [based-ghost/react-functional-select#20] opened 2020-11-17 21:36 UTC
Hi,
I've notice that the component is not tab selectable and so it will interfere with accessibility focused software. I've also noted that you've set the tabindex to -1 on the input used to filter.

1. Do you have a plan to address accessibility issues (this one in particular)?
2. Is there a reason for the "-1" as value for tabindex?
3. Would you consider the reset/clear button to be part of the tab index flow too?

**Comment by based-ghost** [comment] 2020-11-21 14:07
@adi-b - yes, good catch - "2" is actually the cause of "1" and should get a `tabIndex` of 0.  In regards to "3", I don't know if it makes sense to include those controls in the `tabIndex` flow as they can be generated from within the library or by a passed element from the consumer (I think this creates too much variability).

I should have PR going out shortly with the fix to address "1" and "2".

Thanks!

**Comment by based-ghost** [comment] 2020-11-21 18:22
@adi-b - fix is now available with latest version of package `react-functional-select@2.9.3`

**Comment by adi-b** [comment] 2020-11-23 19:05
Thanks for your help. I will test it out.

**Comment by based-ghost** [comment] 2020-12-13 02:18
Closing, as I believe this is now resolved - if still an issue, please let me know.

**Closed as completed by based-ghost** 2020-12-13 02:18 UTC
